### ISSUE TITLE
website: one but not three daemon is installed when check status

### ISSUE THREAD

**Issue by Yiyiyimu** [chaos-mesh/chaos-mesh#980] opened 2020-09-25 11:04 UTC
## Bug Report

**What version of Kubernetes are you using?**
v1.18.0

**What did you do?**
Following installation guide and successfully installed chaos mesh on kind. 

**What did you expect to see?**
When check pod installed by `kubectl get pod -n chaos-testing`, only one daemon is showed like
```
NAME                                        READY   STATUS    RESTARTS   AGE
chaos-controller-manager-798ccd78f4-pxxkg   1/1     Running   0          30m
chaos-daemon-k6cgh                          1/1     Running   0          30m
chaos-dashboard-6c98b89c7b-xm45d            1/1     Running   0          30m
```

But on website, there would be [three daemon running](https://chaos-mesh.org/docs/installation/get_started_on_kind/#verify-your-installation), which I think might not the situation for the default installation (cause also only one daemon is running in #899) and would be confusing for the users.

**Comment by zhouqiang-cl** [comment] 2020-09-25 11:08
@Yiyiyimu good catch, would you like to create a pr add a comment or some other fix on the website?

**Comment by Yiyiyimu** [comment] 2020-09-25 11:33
Sure I'll fix it tonight

**Comment by zhouqiang-cl** [comment] 2020-09-25 20:59
It is wired, I have three chaos-daemon, @cwen0 PTAL

**Comment by cwen0** [comment] 2020-09-27 02:34
> It is wired, I have three chaos-daemon, @cwen0 PTAL

The number of chaos-daemon depends on how many Kubernetes nodes we have!

**Comment by cwen0** [comment] 2020-09-27 02:39
I will close this issue because this is not a bug. We can add a note to notify users about this.

**Closed by cwen0** 2020-09-27 02:39 UTC
Labels: good first issue
