### ISSUE TITLE
Support one-time job

### ISSUE THREAD

**Issue by Colstuwjx** [chaos-mesh/chaos-mesh#1301] opened 2020-12-18 06:47 UTC
## Feature Request

**Is your feature request related to a problem? Please describe:**

I want to run a chaos in a certain duration and then let it exit, rather than re-applying it in the nextStart round.

**Describe the feature you'd like:**

A chaos could run in a certain duration and just finish and clean exit like [k8s batch job did](https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically).

**Describe alternatives you've considered:**

Currently, I run the chaos and after it applied in a certain duration, delete it by manually.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Colstuwjx** [comment] 2020-12-18 07:31
Seems related to #501 .

**Comment by STRRL** [comment] 2020-12-18 08:18
> Seems related to #501 .

Yes. I have wanted to implement an "at controller" beside "common controller" and "two-phase controller". But it seems a duplicate of the two-phase controller. 

And we still consider that "scheduling" should be implemented by Workflow, two-phase also will be marked as deprecated after Workflow released.

Do you have any idea about it?😁

**Comment by Colstuwjx** [comment] 2020-12-18 08:33
Yes, I think we should make each chaos controller works like a k8s Job ( a.k.a ad-hoc task ), and implement schedule & orchestration via Workflow.

Mixing the schedule and job into two-phase made the two-phase controller too complicated ( see background from [PR #1221 comment](https://github.com/chaos-mesh/chaos-mesh/pull/1221#discussion_r539888031) )  ...

**Comment by STRRL** [comment] 2022-04-25 14:02
I think this feature has been supported in after v2.0.0, <Any>Chaos only holds `duration`, and the CRD `Schedule` would hold the `cron`

I am going to close this issue.

**Closed by STRRL** 2022-04-25 14:02 UTC
Labels: type/enhancement
