### ISSUE TITLE
Dashboard: Panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Andrewmatilde** [chaos-mesh/chaos-mesh#2273] opened 2021-09-02 09:50 UTC
## Bug Report

**What version of Kubernetes are you using?**
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"

**What version of Chaos Mesh are you using?**
latest / commit: 00ca86a059041aadf0329648d8cb4cc96e94757c

**What did you do?**

Try some dashboard only experiment in a testing nginx pod. The experiment type is network & clock skew.
**Output of dashboard**
```
Chaos Dashboard Version: version.Info{GitVersion:"master-g00ca86a059041a", GitCommit:"00ca86a059041aadf0329648d8cb4cc96e94757c", BuildDate:"2021-08-27T02:58:48Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/amd64"}
2021/09/02 09:43:19 [Fx] PROVIDE        context.Context <= main.main.func1()
2021/09/02 09:43:19 [Fx] PROVIDE        *config.ChaosDashboardConfig <= main.main.func1()
2021/09/02 09:43:19 [Fx] PROVIDE        *ttlcontroller.TTLconfig <= main.main.func1()
2021/09/02 09:43:19 [Fx] PROVIDE        *dbstore.DB <= github.com/chaos-mesh/chaos-mesh/pkg/store/dbstore.NewDBStore()
2021/09/02 09:43:19 [Fx] PROVIDE        *collector.Server <= github.com/chaos-mesh/chaos-mesh/pkg/collector.NewServer()
2021/09/02 09:43:19 [Fx] PROVIDE        client.Client <= github.com/chaos-mesh/chaos-mesh/pkg/collector.NewServer()
2021/09/02 09:43:19 [Fx] PROVIDE        client.Reader <= github.com/chaos-mesh/chaos-mesh/pkg/collector.NewServer()
2021/09/02 09:43:19 [Fx] PROVIDE        *runtime.Scheme <= github.com/chaos-mesh/chaos-mesh/pkg/collector.NewServer()
2021/09/02 09:43:19 [Fx] PROVIDE        *ttlcontroller.Controller <= github.com/chaos-mesh/chaos-mesh/pkg/ttlcontroller.NewController()
2021/09/02 09:43:19 [Fx] PROVIDE        core.ExperimentStore <= github.com/chaos-mesh/chaos-mesh/pkg/store/experiment.NewStore()
2021/09/02 09:43:19 [Fx] PROVIDE        core.EventStore <= github.com/chaos-mesh/chaos-mesh/pkg/store/event.NewStore()
2021/09/02 09:43:19 [Fx] PROVIDE        core.ScheduleStore <= github.com/chaos-mesh/chaos-mesh/pkg/store/schedule.NewStore()
2021/09/02 09:43:19 [Fx] PROVIDE        core.WorkflowStore <= github.com/chaos-mesh/chaos-mesh/pkg/store/workflow.NewStore()
2021/09/02 09:43:19 [Fx] PROVIDE        *gin.Engine <= github.com/chaos-mesh/chaos-mesh/pkg/apiserver.newEngine()
2021/09/02 09:43:19 [Fx] PROVIDE        *gin.RouterGroup <= github.com/chaos-mesh/chaos-mesh/pkg/apiserver.newAPIRouter()
2021/09/02 09:43:19 [Fx] PROVIDE        *common.Service <= github.com/chaos-mesh/chaos-mesh/pkg/apiserver/common.NewService()
2021/09/02 09:43:19 [Fx] PROVIDE        *experiment.Service <= github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.NewService()
2021/09/02 09:43:19 [Fx] PROVIDE        *event.Service <= github.com/chaos-mesh/chaos-mesh/pkg/apiserver/event.NewService()
2021/09/02 09:43:19 [Fx] PROVIDE        *archive.Service <= github.com/chaos-mesh/chaos-mesh/pkg/apiserver/archive.NewService()
2021/09/02 09:43:19 [Fx] PROVIDE        *workflow.Service <= github.com/chaos-mesh/chaos-mesh/pkg/apiserver/workflow.NewService()
2021/09/02 09:43:19 [Fx] PROVIDE        *schedule.Service <= github.com/chaos-mesh/chaos-mesh/pkg/apiserver/schedule.NewService()
2021/09/02 09:43:19 [Fx] PROVIDE        fx.Lifecycle <= go.uber.org/fx.New.func1()
2021/09/02 09:43:19 [Fx] PROVIDE        fx.Shutdowner <= go.uber.org/fx.(*App).shutdowner-fm()
2021/09/02 09:43:19 [Fx] PROVIDE        fx.DotGraph <= go.uber.org/fx.(*App).dotGraph-fm()
2021/09/02 09:43:19 [Fx] INVOKE         github.com/chaos-mesh/chaos-mesh/pkg/store/experiment.DeleteIncompleteExperiments()
2021/09/02 09:43:19 [Fx] INVOKE         github.com/chaos-mesh/chaos-mesh/pkg/store/schedule.DeleteIncompleteSchedules()
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

2021/09/02 09:43:19 [Fx] INVOKE         github.com/chaos-mesh/chaos-mesh/pkg/apiserver/common.Register()
[GIN-debug] GET    /debug/pprof/             --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/cmdline      --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/profile      --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] POST   /debug/pprof/symbol       --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/symbol       --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/trace        --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/allocs       --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/block        --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/goroutine    --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/heap         --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/mutex        --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/threadcreate --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /                         --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver.newEngine.func1 (4 handlers)
[GIN-debug] GET    /:foo                     --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver.newEngine.func2 (4 handlers)
[GIN-debug] GET    /:foo/*bar                --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver.newEngine.func3 (4 handlers)
[GIN-debug] GET    /static/*any              --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver.newEngine.func4 (4 handlers)
[GIN-debug] GET    /favicon.ico              --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver.newEngine.func4 (4 handlers)
[GIN-debug] GET    /api/swagger/*any         --> github.com/swaggo/gin-swagger.CustomWrapHandler.func1 (4 handlers)
2021-09-02T09:43:19.310Z        INFO    collector       Chaos controller manager is running in cluster scoped mode.
2021-09-02T09:43:19.620Z        INFO    controller-runtime.metrics      metrics server is starting to listen    {"addr": ":8080"}
[GIN-debug] POST   /api/common/pods          --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/common.(*Service).listPods-fm (4 handlers)
[GIN-debug] GET    /api/common/namespaces    --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/common.(*Service).listNamespaces-fm (4 handlers)
[GIN-debug] GET    /api/common/chaos-available-namespaces --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/common.(*Service).getChaosAvailableNamespaces-fm (4 handlers)
[GIN-debug] GET    /api/common/kinds         --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/common.(*Service).getKinds-fm (4 handlers)
[GIN-debug] GET    /api/common/labels        --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/common.(*Service).getLabels-fm (4 handlers)
[GIN-debug] GET    /api/common/annotations   --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/common.(*Service).getAnnotations-fm (4 handlers)
[GIN-debug] GET    /api/common/config        --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/common.(*Service).getConfig-fm (4 handlers)
[GIN-debug] GET    /api/common/rbac-config   --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/common.(*Service).getRbacConfig-fm (4 handlers)
[GIN-debug] GET    /api/experiments          --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.(*Service).listExperiments-fm (4 handlers)
[GIN-debug] POST   /api/experiments/new      --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.(*Service).createExperiment-fm (4 handlers)
[GIN-debug] GET    /api/experiments/detail/:uid --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.(*Service).getExperimentDetail-fm (4 handlers)
[GIN-debug] DELETE /api/experiments/:uid     --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.(*Service).deleteExperiment-fm (4 handlers)
[GIN-debug] DELETE /api/experiments/         --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.(*Service).batchDeleteExperiment-fm (4 handlers)
[GIN-debug] PUT    /api/experiments/update   --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.(*Service).updateExperiment-fm (4 handlers)
[GIN-debug] PUT    /api/experiments/pause/:uid --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.(*Service).pauseExperiment-fm (4 handlers)
[GIN-debug] PUT    /api/experiments/start/:uid --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.(*Service).startExperiment-fm (4 handlers)
[GIN-debug] GET    /api/experiments/state    --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.(*Service).state-fm (4 handlers)
[GIN-debug] GET    /api/events               --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/event.(*Service).listEvents-fm (5 handlers)
[GIN-debug] GET    /api/events/get           --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/event.(*Service).getEvent-fm (5 handlers)
2021/09/02 09:43:19 [Fx] INVOKE         github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.Register()
2021/09/02 09:43:19 [Fx] INVOKE         github.com/chaos-mesh/chaos-mesh/pkg/apiserver/event.Register()
2021/09/02 09:43:19 [Fx] INVOKE         github.com/chaos-mesh/chaos-mesh/pkg/apiserver/archive.Register()
[GIN-debug] GET    /api/archives             --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/archive.(*Service).list-fm (5 handlers)
[GIN-debug] GET    /api/archives/detail      --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/archive.(*Service).detail-fm (5 handlers)
[GIN-debug] DELETE /api/archives/:uid        --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/archive.(*Service).delete-fm (5 handlers)
[GIN-debug] DELETE /api/archives/            --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/archive.(*Service).batchDelete-fm (5 handlers)
[GIN-debug] GET    /api/archives/schedules   --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/archive.(*Service).listSchedule-fm (5 handlers)
[GIN-debug] GET    /api/archives/schedules/:uid --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/archive.(*Service).detailSchedule-fm (5 handlers)
[GIN-debug] DELETE /api/archives/schedules/:uid --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/archive.(*Service).deleteSchedule-fm (5 handlers)
[GIN-debug] DELETE /api/archives/schedules   --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/archive.(*Service).batchDeleteSchedule-fm (5 handlers)
[GIN-debug] GET    /api/archives/workflows   --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/archive.(*Service).listWorkflow-fm (5 handlers)
[GIN-debug] GET    /api/archives/workflows/:uid --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/archive.(*Service).detailWorkflow-fm (5 handlers)
[GIN-debug] DELETE /api/archives/workflows/:uid --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/archive.(*Service).deleteWorkflow-fm (5 handlers)
[GIN-debug] DELETE /api/archives/workflows   --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/archive.(*Service).batchDeleteWorkflow-fm (5 handlers)
2021/09/02 09:43:19 [Fx] INVOKE         github.com/chaos-mesh/chaos-mesh/pkg/apiserver/workflow.Register()
[GIN-debug] GET    /api/workflows            --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/workflow.(*Service).listWorkflows-fm (4 handlers)
[GIN-debug] POST   /api/workflows            --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/workflow.(*Service).createWorkflow-fm (4 handlers)
[GIN-debug] GET    /api/workflows/:uid       --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/workflow.(*Service).getWorkflowDetailByUID-fm (4 handlers)
[GIN-debug] PUT    /api/workflows/:uid       --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/workflow.(*Service).updateWorkflow-fm (4 handlers)
[GIN-debug] DELETE /api/workflows/:uid       --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/workflow.(*Service).deleteWorkflow-fm (4 handlers)
2021/09/02 09:43:19 [Fx] INVOKE         github.com/chaos-mesh/chaos-mesh/pkg/apiserver/schedule.Register()
[GIN-debug] GET    /api/schedules            --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/schedule.(*Service).listSchedules-fm (4 handlers)
[GIN-debug] GET    /api/schedules/:uid       --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/schedule.(*Service).getScheduleDetail-fm (4 handlers)
[GIN-debug] POST   /api/schedules/           --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/schedule.(*Service).createSchedule-fm (4 handlers)
[GIN-debug] PUT    /api/schedules/           --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/schedule.(*Service).updateSchedule-fm (4 handlers)
[GIN-debug] DELETE /api/schedules/:uid       --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/schedule.(*Service).deleteSchedule-fm (4 handlers)
[GIN-debug] DELETE /api/schedules/           --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/schedule.(*Service).batchDeleteSchedule-fm (4 handlers)
[GIN-debug] PUT    /api/schedules/pause/:uid --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/schedule.(*Service).pauseSchedule-fm (4 handlers)
[GIN-debug] PUT    /api/schedules/start/:uid --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/schedule.(*Service).startSchedule-fm (4 handlers)
2021/09/02 09:43:19 [Fx] INVOKE         github.com/chaos-mesh/chaos-mesh/pkg/apiserver.serverRegister()
2021/09/02 09:43:19 [Fx] INVOKE         github.com/chaos-mesh/chaos-mesh/pkg/collector.Register()
2021/09/02 09:43:19 [Fx] INVOKE         github.com/chaos-mesh/chaos-mesh/pkg/ttlcontroller.Register()
2021-09-02T09:43:19.924Z        INFO    database ttl controller starting database TTL controller
[GIN-debug] Listening and serving HTTP on 0.0.0.0:2333
2021/09/02 09:43:19 [Fx] RUNNING
2021-09-02T09:43:19.924Z        INFO    collector       Starting collector
2021-09-02T09:43:19.924Z        INFO    database ttl controller deleting expired data from the database
2021-09-02T09:43:19.925Z        INFO    controller-runtime.manager      starting metrics server {"path": "/metrics"}
2021-09-02T09:43:19.925Z        INFO    controller-runtime.manager.controller.networkchaos      Starting EventSource    {"reconciler group": "chaos-mesh.org", "reconciler kind": "NetworkChaos", "source": "kind source: /, Kind="}
2021-09-02T09:43:19.925Z        INFO    controller-runtime.manager.controller.networkchaos      Starting Controller     {"reconciler group": "chaos-mesh.org", "reconciler kind": "NetworkChaos"}
2021-09-02T09:43:19.925Z        INFO    controller-runtime.manager.controller.stresschaos       Starting EventSource    {"reconciler group": "chaos-mesh.org", "reconciler kind": "StressChaos", "source": "kind source: /, Kind="}
2021-09-02T09:43:19.925Z        INFO    controller-runtime.manager.controller.stresschaos       Starting Controller     {"reconciler group": "chaos-mesh.org", "reconciler kind": "StressChaos"}
2021-09-02T09:43:19.925Z        INFO    controller-runtime.manager.controller.podchaos  Starting EventSource    {"reconciler group": "chaos-mesh.org", "reconciler kind": "PodChaos", "source": "kind source: /, Kind="}
2021-09-02T09:43:19.925Z        INFO    controller-runtime.manager.controller.podchaos  Starting Controller     {"reconciler group": "chaos-mesh.org", "reconciler kind": "PodChaos"}
2021-09-02T09:43:19.925Z        INFO    controller-runtime.manager.controller.awschaos  Starting EventSource    {"reconciler group": "chaos-mesh.org", "reconciler kind": "AWSChaos", "source": "kind source: /, Kind="}
2021-09-02T09:43:19.925Z        INFO    controller-runtime.manager.controller.awschaos  Starting Controller     {"reconciler group": "chaos-mesh.org", "reconciler kind": "AWSChaos"}
2021-09-02T09:43:19.925Z        INFO    controller-runtime.manager.controller.dnschaos  Starting EventSource    {"reconciler group": "chaos-mesh.org", "reconciler kind": "DNSChaos", "source": "kind source: /, Kind="}
2021-09-02T09:43:19.925Z        INFO    controller-runtime.manager.controller.dnschaos  Starting Controller     {"reconciler group": "chaos-mesh.org", "reconciler kind": "DNSChaos"}
2021-09-02T09:43:19.925Z        INFO    controller-runtime.manager.controller.iochaos   Starting EventSource    {"reconciler group": "chaos-mesh.org", "reconciler kind": "IOChaos", "source": "kind source: /, Kind="}
2021-09-02T09:43:19.925Z        INFO    controller-runtime.manager.controller.iochaos   Starting Controller     {"reconciler group": "chaos-mesh.org", "reconciler kind": "IOChaos"}
2021-09-02T09:43:19.925Z        INFO    controller-runtime.manager.controller.timechaos Starting EventSource    {"reconciler group": "chaos-mesh.org", "reconciler kind": "TimeChaos", "source": "kind source: /, Kind="}
2021-09-02T09:43:19.925Z        INFO    controller-runtime.manager.controller.timechaos Starting Controller     {"reconciler group": "chaos-mesh.org", "reconciler kind": "TimeChaos"}
2021-09-02T09:43:19.926Z        INFO    controller-runtime.manager.controller.gcpchaos  Starting EventSource    {"reconciler group": "chaos-mesh.org", "reconciler kind": "GCPChaos", "source": "kind source: /, Kind="}
2021-09-02T09:43:19.926Z        INFO    controller-runtime.manager.controller.gcpchaos  Starting Controller     {"reconciler group": "chaos-mesh.org", "reconciler kind": "GCPChaos"}
2021-09-02T09:43:19.926Z        INFO    controller-runtime.manager.controller.httpchaos Starting EventSource    {"reconciler group": "chaos-mesh.org", "reconciler kind": "HTTPChaos", "source": "kind source: /, Kind="}
2021-09-02T09:43:19.926Z        INFO    controller-runtime.manager.controller.httpchaos Starting Controller     {"reconciler group": "chaos-mesh.org", "reconciler kind": "HTTPChaos"}
2021-09-02T09:43:19.926Z        INFO    controller-runtime.manager.controller.jvmchaos  Starting EventSource    {"reconciler group": "chaos-mesh.org", "reconciler kind": "JVMChaos", "source": "kind source: /, Kind="}
2021-09-02T09:43:19.926Z        INFO    controller-runtime.manager.controller.jvmchaos  Starting Controller     {"reconciler group": "chaos-mesh.org", "reconciler kind": "JVMChaos"}
2021-09-02T09:43:19.926Z        INFO    controller-runtime.manager.controller.kernelchaos       Starting EventSource    {"reconciler group": "chaos-mesh.org", "reconciler kind": "KernelChaos", "source": "kind source: /, Kind="}
2021-09-02T09:43:19.926Z        INFO    controller-runtime.manager.controller.kernelchaos       Starting Controller     {"reconciler group": "chaos-mesh.org", "reconciler kind": "KernelChaos"}
2021-09-02T09:43:19.926Z        INFO    controller-runtime.manager.controller.schedule  Starting EventSource    {"reconciler group": "chaos-mesh.org", "reconciler kind": "Schedule", "source": "kind source: /, Kind="}
2021-09-02T09:43:19.926Z        INFO    controller-runtime.manager.controller.schedule  Starting Controller     {"reconciler group": "chaos-mesh.org", "reconciler kind": "Schedule"}
2021-09-02T09:43:19.926Z        INFO    controller-runtime.manager.controller.event     Starting EventSource    {"reconciler group": "", "reconciler kind": "Event", "source": "kind source: /, Kind="}
2021-09-02T09:43:19.926Z        INFO    controller-runtime.manager.controller.event     Starting Controller     {"reconciler group": "", "reconciler kind": "Event"}
2021-09-02T09:43:19.926Z        INFO    controller-runtime.manager.controller.workflow  Starting EventSource    {"reconciler group": "chaos-mesh.org", "reconciler kind": "Workflow", "source": "kind source: /, Kind="}
2021-09-02T09:43:19.926Z        INFO    controller-runtime.manager.controller.workflow  Starting Controller     {"reconciler group": "chaos-mesh.org", "reconciler kind": "Workflow"}
2021-09-02T09:43:20.025Z        INFO    controller-runtime.manager.controller.stresschaos       Starting workers        {"reconciler group": "chaos-mesh.org", "reconciler kind": "StressChaos", "worker count": 1}
2021-09-02T09:43:20.026Z        INFO    controller-runtime.manager.controller.dnschaos  Starting workers        {"reconciler group": "chaos-mesh.org", "reconciler kind": "DNSChaos", "worker count": 1}
2021-09-02T09:43:20.026Z        INFO    controller-runtime.manager.controller.gcpchaos  Starting workers        {"reconciler group": "chaos-mesh.org", "reconciler kind": "GCPChaos", "worker count": 1}
2021-09-02T09:43:20.027Z        INFO    controller-runtime.manager.controller.kernelchaos       Starting workers        {"reconciler group": "chaos-mesh.org", "reconciler kind": "KernelChaos", "worker count": 1}
2021-09-02T09:43:20.027Z        INFO    controller-runtime.manager.controller.httpchaos Starting workers        {"reconciler group": "chaos-mesh.org", "reconciler kind": "HTTPChaos", "worker count": 1}
2021-09-02T09:43:20.027Z        INFO    controller-runtime.manager.controller.workflow  Starting workers        {"reconciler group": "chaos-mesh.org", "reconciler kind": "Workflow", "worker count": 1}
2021-09-02T09:43:20.027Z        INFO    controller-runtime.manager.controller.podchaos  Starting workers        {"reconciler group": "chaos-mesh.org", "reconciler kind": "PodChaos", "worker count": 1}
2021-09-02T09:43:20.027Z        INFO    controller-runtime.manager.controller.iochaos   Starting workers        {"reconciler group": "chaos-mesh.org", "reconciler kind": "IOChaos", "worker count": 1}
2021-09-02T09:43:20.027Z        INFO    controller-runtime.manager.controller.schedule  Starting workers        {"reconciler group": "chaos-mesh.org", "reconciler kind": "Schedule", "worker count": 1}
2021-09-02T09:43:20.028Z        INFO    controller-runtime.manager.controller.timechaos Starting workers        {"reconciler group": "chaos-mesh.org", "reconciler kind": "TimeChaos", "worker count": 1}
2021-09-02T09:43:20.028Z        INFO    controller-runtime.manager.controller.jvmchaos  Starting workers        {"reconciler group": "chaos-mesh.org", "reconciler kind": "JVMChaos", "worker count": 1}
2021-09-02T09:43:20.028Z        INFO    controller-runtime.manager.controller.networkchaos      Starting workers        {"reconciler group": "chaos-mesh.org", "reconciler kind": "NetworkChaos", "worker count": 1}
2021-09-02T09:43:20.028Z        INFO    controller-runtime.manager.controller.event     Starting workers        {"reconciler group": "", "reconciler kind": "Event", "worker count": 1}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1ae483a]

goroutine 579 [running]:
github.com/chaos-mesh/chaos-mesh/api/v1alpha1.(*ChaosKind).SpawnObject(...)
        /mnt/api/v1alpha1/kinds.go:72
github.com/chaos-mesh/chaos-mesh/pkg/collector.(*EventCollector).Reconcile(0xc00074cdc0, 0x2634460, 0xc001d29200, 0xc00184a327, 0x7, 0xc001342e40, 0x32, 0xc001d29200, 0x411ddf, 0xc0006b4000, ...)
        /mnt/pkg/collector/event_collector.go:58 +0x1fa
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00044e280, 0x26343a0, 0xc00190bfc0, 0x1e33120, 0xc001d3a980)
        /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:298 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00044e280, 0x26343a0, 0xc00190bfc0, 0x0)
        /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc000718fe0, 0xc00044e280, 0x26343a0, 0xc00190bfc0)
        /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:210 +0x46b
```

**Comment by cwen0** [comment] 2021-09-11 05:35
@Andrewmatilde This issue has been fixed in #2218, so I close it now. 

This issue was caused by the that we used the type before checking the result of type assertion. If type assertion returns false, the progress will panic. https://github.com/chaos-mesh/chaos-mesh/blob/00ca86a059041aadf0329648d8cb4cc96e94757c/pkg/collector/event_collector.go#L57-L60 

fixed: 

https://github.com/chaos-mesh/chaos-mesh/blob/f6143ab7be0f655112064330cf3df581406c2c1f/pkg/collector/event_collector.go#L57-L59

**Closed** 2021-09-11 05:35 UTC
Labels: type/bug, component/chaos-dashboard
