### ISSUE TITLE
chaos-controller-manager: memory keeps increasing 

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#3761] opened 2022-11-07 09:07 UTC
## Bug Report

**What version of Kubernetes are you using?**

**What version of Chaos Mesh are you using?**
 

v2.4.1

**What did you do? / Minimal Reproducible Example**

**What did you expect to see?**

**What did you see instead?**  

![img_v2_9c2c1f15-274c-43ea-9286-d1871da3fb4g](https://user-images.githubusercontent.com/22956341/200270172-690f230b-4074-4799-8328-58f5ef80c3e0.jpg)

```
Controller manager Version: version.Info{GitVersion:"v2.1.4", GitCommit:"7ef267c9e912cdae32dbedc4bd70a4fb546ac3f5", BuildDate:"2022-03-22T07:15:11Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
2022-11-07T07:17:40.221Z        INFO    fx      fxlog/fxlog.go:65       [Fx] SUPPLY     *prometheus.Registry
2022-11-07T07:17:40.221Z        INFO    fx      fxlog/fxlog.go:65       [Fx] SUPPLY     logr.Logger
2022-11-07T07:17:40.221Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *metrics.ChaosControllerManagerMetricsCollector <= github.com/chaos-mesh/chaos-mesh/pkg/metrics.NewChaosControllerManagerMetricsCollector()
2022-11-07T07:17:40.221Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *manager.Options <= github.com/chaos-mesh/chaos-mesh/cmd/chaos-controller-manager/provider.NewOption()
2022-11-07T07:17:40.221Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    client.Client <= github.com/chaos-mesh/chaos-mesh/cmd/chaos-controller-manager/provider.NewClient()
2022-11-07T07:17:40.221Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *kubernetes.Clientset <= github.com/chaos-mesh/chaos-mesh/cmd/chaos-controller-manager/provider.NewClientSet()
2022-11-07T07:17:40.221Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    manager.Manager <= github.com/chaos-mesh/chaos-mesh/cmd/chaos-controller-manager/provider.NewManager()
2022-11-07T07:17:40.221Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *v1.AuthorizationV1Client <= github.com/chaos-mesh/chaos-mesh/cmd/chaos-controller-manager/provider.NewAuthCli()
2022-11-07T07:17:40.221Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *runtime.Scheme <= github.com/chaos-mesh/chaos-mesh/cmd/chaos-controller-manager/provider.NewScheme()
2022-11-07T07:17:40.221Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *rest.Config <= github.com/chaos-mesh/chaos-mesh/cmd/chaos-controller-manager/provider.NewConfig()
2022-11-07T07:17:40.221Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    client.Reader:no-cache <= github.com/chaos-mesh/chaos-mesh/cmd/chaos-controller-manager/provider.NewNoCacheReader()
2022-11-07T07:17:40.221Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    client.Reader:global-cache <= github.com/chaos-mesh/chaos-mesh/cmd/chaos-controller-manager/provider.NewGlobalCacheReader()
2022-11-07T07:17:40.221Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    client.Reader:control-plane-cache <= github.com/chaos-mesh/chaos-mesh/cmd/chaos-controller-manager/provider.NewControlPlaneCacheReader()
2022-11-07T07:17:40.221Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *chaosdaemon.ChaosDaemonClientBuilder <= github.com/chaos-mesh/chaos-mesh/controllers/utils/chaosdaemon.New()
2022-11-07T07:17:40.221Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *recorder.RecorderBuilder <= github.com/chaos-mesh/chaos-mesh/controllers/utils/recorder.NewRecorderBuilder()
2022-11-07T07:17:40.221Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    []pipeline.PipelineStep <= github.com/chaos-mesh/chaos-mesh/controllers/common.AllSteps()
2022-11-07T07:17:40.222Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *utils.ActiveLister <= github.com/chaos-mesh/chaos-mesh/controllers/schedule/utils.NewActiveLister()
2022-11-07T07:17:40.222Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *detachvolume.Impl <= github.com/chaos-mesh/chaos-mesh/controllers/chaosimpl/awschaos/detachvolume.NewImpl()
2022-11-07T07:17:40.222Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *ec2restart.Impl <= github.com/chaos-mesh/chaos-mesh/controllers/chaosimpl/awschaos/ec2restart.NewImpl()
2022-11-07T07:17:40.222Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *ec2stop.Impl <= github.com/chaos-mesh/chaos-mesh/controllers/chaosimpl/awschaos/ec2stop.NewImpl()
2022-11-07T07:17:40.222Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *podhttpchaosmanager.Builder <= github.com/chaos-mesh/chaos-mesh/controllers/chaosimpl/httpchaos/podhttpchaosmanager.NewBuilder()
2022-11-07T07:17:40.222Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *podiochaosmanager.Builder <= github.com/chaos-mesh/chaos-mesh/controllers/chaosimpl/iochaos/podiochaosmanager.NewBuilder()
2022-11-07T07:17:40.222Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *trafficcontrol.Impl <= github.com/chaos-mesh/chaos-mesh/controllers/chaosimpl/networkchaos/trafficcontrol.NewImpl()
2022-11-07T07:17:40.222Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *partition.Impl <= github.com/chaos-mesh/chaos-mesh/controllers/chaosimpl/networkchaos/partition.NewImpl()
2022-11-07T07:17:40.222Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *podnetworkchaosmanager.Builder <= github.com/chaos-mesh/chaos-mesh/controllers/chaosimpl/networkchaos/podnetworkchaosmanager.NewBuilder()
2022-11-07T07:17:40.222Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *podkill.Impl <= github.com/chaos-mesh/chaos-mesh/controllers/chaosimpl/podchaos/podkill.NewImpl()
2022-11-07T07:17:40.222Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *podfailure.Impl <= github.com/chaos-mesh/chaos-mesh/controllers/chaosimpl/podchaos/podfailure.NewImpl()
2022-11-07T07:17:40.222Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *containerkill.Impl <= github.com/chaos-mesh/chaos-mesh/controllers/chaosimpl/podchaos/containerkill.NewImpl()
2022-11-07T07:17:40.222Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *diskloss.Impl <= github.com/chaos-mesh/chaos-mesh/controllers/chaosimpl/gcpchaos/diskloss.NewImpl()
2022-11-07T07:17:40.222Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *nodereset.Impl <= github.com/chaos-mesh/chaos-mesh/controllers/chaosimpl/gcpchaos/nodereset.NewImpl()
2022-11-07T07:17:40.222Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *nodestop.Impl <= github.com/chaos-mesh/chaos-mesh/controllers/chaosimpl/gcpchaos/nodestop.NewImpl()
2022-11-07T07:17:40.222Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *utils.ContainerRecordDecoder <= github.com/chaos-mesh/chaos-mesh/controllers/chaosimpl/utils.NewContainerRecordDecoder()
2022-11-07T07:17:40.222Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *selector.Selector <= github.com/chaos-mesh/chaos-mesh/pkg/selector.New()
2022-11-07T07:17:40.222Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *pod.SelectImpl <= github.com/chaos-mesh/chaos-mesh/pkg/selector/pod.New()
2022-11-07T07:17:40.223Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *container.SelectImpl <= github.com/chaos-mesh/chaos-mesh/pkg/selector/container.New()
2022-11-07T07:17:40.223Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *aws.SelectImpl <= github.com/chaos-mesh/chaos-mesh/pkg/selector/aws.New()
2022-11-07T07:17:40.223Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *gcp.SelectImpl <= github.com/chaos-mesh/chaos-mesh/pkg/selector/gcp.New()
2022-11-07T07:17:40.223Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    *physicalmachine.SelectImpl <= github.com/chaos-mesh/chaos-mesh/pkg/selector/physicalmachine.New()
2022-11-07T07:17:40.223Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    fx.Lifecycle <= go.uber.org/fx.New.func1()
2022-11-07T07:17:40.223Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    fx.Shutdowner <= go.uber.org/fx.(*App).shutdowner-fm()
2022-11-07T07:17:40.223Z        INFO    fx      fxlog/fxlog.go:57       [Fx] PROVIDE    fx.DotGraph <= go.uber.org/fx.(*App).dotGraph-fm()
2022-11-07T07:17:40.223Z        INFO    fx      fx@v1.12.0/app.go:651   [Fx] INVOKE             github.com/chaos-mesh/chaos-mesh/controllers/common.Bootstrap()
2022-11-07T07:17:40.223Z        INFO    setup   provider/controller.go:85       Chaos controller manager is running in cluster scoped mode.
2022-11-07T07:17:40.258Z        INFO    controller-runtime.metrics      logr@v1.2.0/logr.go:249 Metrics server is starting to listen    {"addr": "0.0.0.0:10080"}
2022-11-07T07:17:40.289Z        INFO    setup-common    common/fx.go:72 setting up controller   {"resource-name": "gcpchaos"}
2022-11-07T07:17:40.289Z        INFO    setup-finalizers        finalizers/step.go:32   setting up controller   {"name": "gcpchaos-finalizers"}
2022-11-07T07:17:40.289Z        INFO    setup-desiredphase      desiredphase/step.go:32 setting up controller   {"name": "gcpchaos-desiredphase"}
2022-11-07T07:17:40.289Z        INFO    setup-condition condition/step.go:32    setting up controller   {"name": "gcpchaos-condition"}
2022-11-07T07:17:40.289Z        INFO    setup-common    common/fx.go:72 setting up controller   {"resource-name": "kernelchaos"}
2022-11-07T07:17:40.289Z        INFO    setup-finalizers        finalizers/step.go:32   setting up controller   {"name": "kernelchaos-finalizers"}
2022-11-07T07:17:40.289Z        INFO    setup-desiredphase      desiredphase/step.go:32 setting up controller   {"name": "kernelchaos-desiredphase"}
2022-11-07T07:17:40.289Z        INFO    setup-condition condition/step.go:32    setting up controller   {"name": "kernelchaos-condition"}
2022-11-07T07:17:40.289Z        INFO    setup-common    common/fx.go:72 setting up controller   {"resource-name": "dnschaos"}
2022-11-07T07:17:40.289Z        INFO    setup-finalizers        finalizers/step.go:32   setting up controller   {"name": "dnschaos-finalizers"}
2022-11-07T07:17:40.289Z        INFO    setup-desiredphase      desiredphase/step.go:32 setting up controller   {"name": "dnschaos-desiredphase"}
2022-11-07T07:17:40.289Z        INFO    setup-condition condition/step.go:32    setting up controller   {"name": "dnschaos-condition"}
...skipping...
github.com/chaos-mesh/chaos-mesh/controllers/common/records.(*Reconciler).Reconcile
        /mnt/controllers/common/records/controller.go:85
github.com/chaos-mesh/chaos-mesh/controllers/common/pipeline.(*Pipeline).Reconcile
        /mnt/controllers/common/pipeline/pipeline.go:73
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
2022-11-07T07:17:55.931Z        INFO    pipeline        pipeline/pipeline.go:78 reconcile result        {"result": {"Requeue":false,"RequeueAfter":0}}
2022-11-07T07:17:55.931Z        INFO    pipeline        pipeline/pipeline.go:78 reconcile result        {"result": {"Requeue":false,"RequeueAfter":0}}
2022-11-07T07:17:55.931Z        INFO    desiredphase    desiredphase/controller.go:130  modify desiredPhase     {"desiredPhase": "Run"}
2022-11-07T07:17:55.931Z        INFO    pipeline        pipeline/pipeline.go:78 reconcile result        {"result": {"Requeue":false,"RequeueAfter":0}}
2022-11-07T07:17:55.932Z        INFO    pipeline        pipeline/pipeline.go:78 reconcile result        {"result": {"Requeue":false,"RequeueAfter":0}}
2022-11-07T07:17:55.932Z        ERROR   records records/controller.go:85        fail to select  {"error": "no pod is selected"}
github.com/chaos-mesh/chaos-mesh/controllers/common/records.(*Reconciler).Reconcile
        /mnt/controllers/common/records/controller.go:85
github.com/chaos-mesh/chaos-mesh/controllers/common/pipeline.(*Pipeline).Reconcile
        /mnt/controllers/common/pipeline/pipeline.go:73
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
2022-11-07T07:17:55.932Z        INFO    pipeline        pipeline/pipeline.go:78 reconcile result        {"result": {"Requeue":false,"RequeueAfter":0}}
2022-11-07T07:17:55.932Z        INFO    pipeline        pipeline/pipeline.go:78 reconcile result        {"result": {"Requeue":false,"RequeueAfter":0}}
2022-11-07T07:17:55.932Z        INFO    desiredphase    desiredphase/controller.go:130  modify desiredPhase     {"desiredPhase": "Run"}
2022-11-07T07:17:55.932Z        INFO    pipeline        pipeline/pipeline.go:78 reconcile result        {"result": {"Requeue":false,"RequeueAfter":0}}
2022-11-07T07:17:55.932Z        INFO    pipeline        pipeline/pipeline.go:78 reconcile result        {"result": {"Requeue":false,"RequeueAfter":0}}
2022-11-07T07:17:55.932Z        ERROR   records records/controller.go:85        fail to select  {"error": "no pod is selected"}
github.com/chaos-mesh/chaos-mesh/controllers/common/records.(*Reconciler).Reconcile
        /mnt/controllers/common/records/controller.go:85
github.com/chaos-mesh/chaos-mesh/controllers/common/pipeline.(*Pipeline).Reconcile
        /mnt/controllers/common/pipeline/pipeline.go:73
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
2022-11-07T07:17:55.932Z        INFO    pipeline        pipeline/pipeline.go:78 reconcile result        {"result": {"Requeue":false,"RequeueAfter":0}}
2022-11-07T07:17:55.932Z        INFO    pipeline        pipeline/pipeline.go:78 reconcile result        {"result": {"Requeue":false,"RequeueAfter":0}}
2022-11-07T07:17:55.932Z        INFO    desiredphase    desiredphase/controller.go:130  modify desiredPhase     {"desiredPhase": "Run"}
2022-11-07T07:17:55.932Z        INFO    pipeline        pipeline/pipeline.go:78 reconcile result        {"result": {"Requeue":false,"RequeueAfter":0}}
2022-11-07T07:17:55.932Z        INFO    pipeline        pipeline/pipeline.go:78 reconcile result        {"result": {"Requeue":false,"RequeueAfter":0}}
2022-11-07T07:17:55.932Z        ERROR   records records/controller.go:85        fail to select  {"error": "no pod is selected"}
github.com/chaos-mesh/chaos-mesh/controllers/common/records.(*Reconciler).Reconcile
        /mnt/controllers/common/records/controller.go:85
github.com/chaos-mesh/chaos-mesh/controllers/common/pipeline.(*Pipeline).Reconcile
        /mnt/controllers/common/pipeline/pipeline.go:73
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
2022-11-07T07:17:55.932Z        INFO    pipeline        pipeline/pipeline.go:78 reconcile result        {"result": {"Requeue":false,"RequeueAfter":0}}
I1107 07:17:56.886350       1 request.go:665] Waited for 1.010160615s due to client-side throttling, not priority and fairness, request: POST:https://172.20.0.1:443/api/v1/namespaces/chaos-testing/events
I1107 07:18:06.911412       1 request.go:665] Waited for 10.031230553s due to client-side throttling, not priority and fairness, request: POST:https://172.20.0.1:443/api/v1/namespaces/chaos-testing/events
I1107 07:18:16.947103       1 request.go:665] Waited for 19.064485164s due to client-side throttling, not priority and fairness, request: POST:https://172.20.0.1:443/api/v1/namespaces/chaos-testing/events
I1107 07:18:26.977577       1 request.go:665] Waited for 27.089388658s due to client-side throttling, not priority and fairness, request: POST:https://172.20.0.1:443/api/v1/namespaces/chaos-testing/events
I1107 07:18:36.978383       1 request.go:665] Waited for 35.085107146s due to client-side throttling, not priority and fairness, request: POST:https://172.20.0.1:443/api/v1/namespaces/chaos-testing/events
``` 
**Output of chaosctl**

   

pprof: 

![image](https://user-images.githubusercontent.com/22956341/200270651-70f5c747-37d8-4bc6-9c7d-b721b3c68dbe.png)
![image](https://user-images.githubusercontent.com/22956341/200270804-815dfd58-0b60-4cdd-8ef9-ad5e813ff48a.png)

**Comment by cwen0** [comment] 2022-11-07 10:10
more log: 

```
message="2022-11-07T08:56:35.587Z\tERROR\tevent-recorder-schedule-gc\trecorder/recorder.go:73\tfail to submit event\t{\"event\": \"&Event{ObjectMeta:{pod-kill-prometheus-operator.17253f98a9cf9ee3  chaos-testing    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[chaos-mesh.org/running-name:pod-kill-prometheus-operator-xnhtn chaos-mesh.org/type:schedule-skip-remove-history] [] []  []},InvolvedObject:ObjectReference{Kind:Schedule,Namespace:chaos-testing,Name:pod-kill-prometheus-operator,UID:992af3b7-b74c-4a69-aa4e-fbe785472c48,APIVersion:chaos-mesh.org/v1alpha1,ResourceVersion:89497187,FieldPath:,},Reason:Skip,Message:Skip removing history: pod-kill-prometheus-operator-xnhtn is still running,Source:EventSource{Component:schedule-gc,Host:,},FirstTimestamp:2022-11-07 08:19:21.927171811 +0000 UTC m=+468.272879945,LastTimestamp:2022-11-07 08:19:21.927171811 +0000 UTC m=+468.272879945,Count:1,Type:Warning,EventTime:0001-01-01 00:00:00 +0000 UTC,Series:nil,Action:,Related:nil,ReportingController:,ReportingInstance:,}\", \"error\": \"Unauthorized\"}"
--

```

**Comment by cwen0** [comment] 2022-11-07 10:10
more log: 

```
message="2022-11-07T08:56:35.587Z\tERROR\tevent-recorder-schedule-gc\trecorder/recorder.go:73\tfail to submit event\t{\"event\": \"&Event{ObjectMeta:{pod-kill-prometheus-operator.17253f98a9cf9ee3  chaos-testing    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[chaos-mesh.org/running-name:pod-kill-prometheus-operator-xnhtn chaos-mesh.org/type:schedule-skip-remove-history] [] []  []},InvolvedObject:ObjectReference{Kind:Schedule,Namespace:chaos-testing,Name:pod-kill-prometheus-operator,UID:992af3b7-b74c-4a69-aa4e-fbe785472c48,APIVersion:chaos-mesh.org/v1alpha1,ResourceVersion:89497187,FieldPath:,},Reason:Skip,Message:Skip removing history: pod-kill-prometheus-operator-xnhtn is still running,Source:EventSource{Component:schedule-gc,Host:,},FirstTimestamp:2022-11-07 08:19:21.927171811 +0000 UTC m=+468.272879945,LastTimestamp:2022-11-07 08:19:21.927171811 +0000 UTC m=+468.272879945,Count:1,Type:Warning,EventTime:0001-01-01 00:00:00 +0000 UTC,Series:nil,Action:,Related:nil,ReportingController:,ReportingInstance:,}\", \"error\": \"Unauthorized\"}"
--

```

**Comment by STRRL** [comment] 2022-11-08 07:06
We do not restrict memory usage by `limit`, I do not think that's a bug.

![Uploading image.png…]()

**Comment by cwen0** [comment] 2022-11-08 07:13
> We do not restrict memory usage with `limit` by default, I do not think that's a bug.
> 
> <img alt="image" width="941" src="https://user-images.githubusercontent.com/20221408/200497190-ab231519-8c64-497a-8a41-d3840dd1a389.png">

This issue was caused by an schedule podchaos. The chaos experiments generated by the schedule podchaos can't finish regularly and chaos mesh will write so many events. The memory was burned by these enevts. I am considering if these events were necessary.

**Comment by cwen0** [comment] 2022-11-08 07:14
> We do not restrict memory usage with `limit` by default, I do not think that's a bug.
> 
> <img alt="image" width="941" src="https://user-images.githubusercontent.com/20221408/200497190-ab231519-8c64-497a-8a41-d3840dd1a389.png">

If we set the memory limit, chaos-controller-manager will be restart due to oom

**Comment by STRRL** [comment] 2022-11-08 07:45
How to reproduce this issue ?

**Comment by cwen0** [comment] 2022-11-08 07:48
> How to reproduce this issue ?

You can try this config ( make sure the target pod not exist): 
```
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: schedule-pod-kill-example
spec:
  schedule: "@every 5s"
  type: "PodChaos"
  concurrencyPolicy: Allow
  podChaos:
    action: "pod-kill"
    mode: one
    selector:
      labelSelectors:
        "app.kubernetes.io/component": "tikv"
```

**Comment by cwen0** [comment] 2022-11-08 07:59
In this pr https://github.com/chaos-mesh/chaos-mesh/pull/3767, I will set the period time to clean finished experiments to 10 minutes, this solution just slows down the speed of burn memory and can't fix this issue completely. @YangKeao @STRRL What do you think?

**Comment by STRRL** [comment] 2022-11-08 13:15
That's my profiling conclusion: **memory increasing is caused by unlimited goroutine spawned with its stack**

https://github.com/chaos-mesh/chaos-mesh/blob/9918756f66a0f71693465a44214dba53a9394fad/controllers/utils/recorder/recorder.go#L72-L79

and these goroutines could not be completed because of the Kubernetes Client client-side throttling. 


I found that the `pprof/heap` only shows little memory usage, so I take a look on `pprof/allocs` and `pprof/goroutine`. I found that there are `11606` gouroutines and `11000` of them are pending with `github.com/chaos-mesh/chaos-mesh/controllers/utils/recorder.(*chaosRecorder).Event.func1`. Also `pprof/allocs` shows me the biggest memory allocating is `runtime/pprof.writeGoroutineStacks`.

And it seems that the allocation of the object escaped from the heap to the stack, with the goroutine number increasing, the memory keeps increasing.

**Comment by STRRL** [comment] 2022-11-08 13:19
I am not sure about #3767 would works, the default `requeueAfter` is 1 second, but the speed of goroutine increasing is much more bigger than that.

I would checkout that PR and make a try.

**Comment by STRRL** [comment] 2022-11-08 13:32
> I am not sure about #3767 would works, the default `requeueAfter` is 1 second, but the speed of goroutine increasing is much more bigger than that.
> 
> I would checkout that PR and make a try.

It does NOT works. The gouroutine still increasing extremely fast and the pod got OOMKilled:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/20221408/200577742-7e9c1473-8b71-4cfb-a65f-dfcab7827fa9.png">
<img width="684" alt="image" src="https://user-images.githubusercontent.com/20221408/200577778-2073eed5-196c-4a5b-961b-06c5a2669118.png">

**Comment by STRRL** [comment] 2022-11-08 13:41
>I am not sure about https://github.com/chaos-mesh/chaos-mesh/pull/3767 would works, the default requeueAfter is 1 second, but the speed of goroutine increasing is much more bigger than that.

The reconcile of the schedule is not only triggered by the `requeue` and `requeueAfter`, but also triggered by the `Owned Objects`:

https://github.com/chaos-mesh/chaos-mesh/blob/9918756f66a0f71693465a44214dba53a9394fad/controllers/schedule/gc/controller.go#L155-158

So only changing `requeueAfter` just does not work.

---

For fixing this issue, what about using the origin client to emit events?

Using events without aggregation has been confirmed as anti-pattern and abuse.

And we have already merged https://github.com/chaos-mesh/chaos-mesh/pull/3170, it could replace the purpose of origin `Event`. 

And at least, the increment of that field is limited with API throttling and reconcile requeue backoff.

**Comment by STRRL** [comment] 2022-11-08 13:41
> For fixing this issue, what about using the origin client to emit events?

cc @YangKeao @cwen0

**Comment by cwen0** [comment] 2022-11-08 14:10
> I am not sure about #3767 would works, the default `requeueAfter` is 1 second, but the speed of goroutine increasing is much more bigger than that.
> 

If the schedule experiment generates 100 histories, the controller will generate 100 goroutines every `requeueAfter` https://github.com/chaos-mesh/chaos-mesh/blob/master/controllers/schedule/gc/controller.go#L86-L105

**Comment by STRRL** [comment] 2022-11-09 00:52
>  Maybe we can ignore this event directly. joy

Agree, what do you think about it? @YangKeao 

But this change only reduce emitting events, the reconcile would still be invoked many times.

**Closed** 2022-11-15 14:27 UTC
Labels: type/bug, component/operator
