### ISSUE TITLE
Invalid `GitVersion`: "v0.0.0-master+$Format:%h$"

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#2659] opened 2021-12-16 09:50 UTC
## Bug Report

**What version of Kubernetes are you using?**
 

1.20.2

**What version of Chaos Mesh are you using?**
 

```
Chaos Dashboard Version: version.Info{GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"e79f3114571122cd3b6991d1faaa66cdcce35a73", BuildDate:"2021-12-15T18:04:31Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

**What did you expect to see?**  

v0.0.0-master-`commit` 

**What did you see instead?** 

v0.0.0-master+$Format:%h$

**Output of chaosctl**

**Comment by cwen0** [comment] 2022-02-10 05:41
@STRRL Are you working on this issue?

**Comment by STRRL** [comment] 2022-02-10 08:29
> @STRRL Are you working on this issue?

Oops, I would try to fix this PR later. 😅

**Comment by STRRL** [comment] 2022-02-10 10:02
I could not reproduce this issue on the master branch. I would close it now, feel free to reopen if it happens again.

**Comment by STRRL** [comment] 2022-02-14 07:42
> @STRRL Hi, I think the problem is related to Github CI, I try to pull the image `ghcr.io/chaos-mesh/chaos-mesh:latest`, and it shows the same result as this issue.
> 
> Look here, [chaos-mesh/chaos-mesh/runs/5145481462?check_suite_focus=true#step:5:1083](https://github.com/chaos-mesh/chaos-mesh/runs/5145481462?check_suite_focus=true#step:5:1083), the `version.gitVersion` is not added to `ldflags`.

I would take a look later!

**Closed** 2022-03-02 03:01 UTC
Labels: type/bug
