### ISSUE TITLE
StressChaos is not injected

### ISSUE THREAD

**Issue by Muscule** [chaos-mesh/chaos-mesh#2178] opened 2021-08-03 11:18 UTC
## Bug Report

**What version of Kubernetes are you using?**
OpenShift 4.7 without access to internet

**What version of Chaos Mesh are you using?**
2.0.0

**What did you do?**
Launched StressChaos Schedule
**What did you expect to see?**
Stressng processes in pod and stresschaos running
**What did you see instead?**
StressChaos in state injecting all the time
**Output of chaosctl**

**Comment by Muscule** [comment] 2021-08-04 07:08
Chaos not found error

**Comment by STRRL** [comment] 2021-08-04 07:55
Hi @Muscule, thanks for your report! 

Could you share the definition of the Schedule for us?

**Comment by Muscule** [comment] 2021-08-04 10:18
​kind: Schedule

apiVersion: chaos-mesh.org/v1alpha1

metadata:

  name: demo-network-stress-memory-label-selected

  namespace: demo-network

spec:

  schedule: '@every 5s'

  startingDeadlineSeconds: null

  concurrencyPolicy: Forbid

  historyLimit: 1

  type: StressChaos

  stressChaos:

    selector:

      namespaces:

        - demo-network

      labelSelectors:

        app: support-tools

    mode: one

    containerNames:

      - ''

    stressors:

      memory:

        workers: 4

        size: 500m

    duration: 1h

**Comment by shyamgcpdemo** [comment] 2021-08-09 17:56
I am also facing the same issue. I would like to add the error message from the Chaos-Dashboard if it would help. 

"Failed to select targets: no record has been selected" 

This could be because the containerNames section is populated as null in the yaml (even in the above example).

Is there an interim fix for this? Or should we wait for an official build?

**Comment by YangKeao** [comment] 2021-08-10 03:23
The problem is that the `containerNames` should be `nil`, or `[]string` with meaningful value, but not `[]string{''}`. It could be a bug in JSON deserialization and I remember it has been fixed. @fewdan  Please investigate and fix this problem ?

**Comment by Muscule** [comment] 2021-09-07 14:26
Is it possible to get info about when this problem will be fixed?

**Comment by fewdan** [comment] 2021-09-10 08:54
This issue was fixed in #2245  , so I closed this issue. If there is a problem, you can reopen this issue at any time.

**Closed by fewdan** 2021-09-10 08:54 UTC
Labels: type/bug
