### ISSUE TITLE
Support experiments can be edited and run again

### ISSUE THREAD

**Issue by wh211212** [chaos-mesh/chaos-mesh#4274] opened 2023-12-05 09:41 UTC
## Feature Request

**Is your feature request related to a problem? Please describe:**

Problem: Now experiment creation is one-time, and it cannot be edited or run again.
Want: Support experiments can be edited and run again.
**Describe the feature you'd like:**

 1. Support experiments can be edited and run again.
 2. support yaml create experiments ，now can use yaml create experiments 
**Describe alternatives you've considered:**

none 
**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by STRRL** [comment] 2023-12-12 14:12
That's by design.
 
Chaos Mesh using CRD to introduce the experiment for the expected states, so one object of CR is exactly "one-time" injection.

We recommend that you could archive this feature by your side with integration with kubernetes API.

Chaos Mesh would not do more things like chaos experiments management.  I am going to close this issue. Fell free to reopen it if you have new idea.Thanks.

**Closed by STRRL** 2023-12-12 14:12 UTC
