### ISSUE TITLE
Unable to install 2.1.3 

### ISSUE THREAD

**Issue by Prashanth-BP** [chaos-mesh/chaos-mesh#3044] opened 2022-03-21 02:02 UTC
hi @iguoyr - I am opening a new Issue further to #2823 (unable to run experiments on version 1.2.2). Now, we are trying to deploy 2.1.3 via Jenkins and get the below error. Any help/suggestions would be appreciated. All our activities are stalled due to previous reported issue (#2823) and now this is the new issue. I have attached the snapshot of the error message.

![Error](https://user-images.githubusercontent.com/47818191/159196634-a5cbc2a4-1ef1-4c11-8598-744ab43a8ee3.jpg)

## Bug Report

**What version of Kubernetes are you using?**
 

**What version of Chaos Mesh are you using?**

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Output of chaosctl**

**Comment by iguoyr** [comment] 2022-03-21 03:54
@Prashanth-BP Hi, could you check the version of chaos-controller-manager image? You could use `kubectl exec -n chaos-testing {chaos-controller-manager-pod-name} -- /usr/local/bin/chaos-controller-manager -version` this command.

**Comment by Prashanth-BP** [comment] 2022-03-21 05:05
> @Prashanth-BP Hi, could you check the version of chaos-controller-manager image? You could use `kubectl exec -n chaos-testing {chaos-controller-manager-pod-name} -- /usr/local/bin/chaos-controller-manager -version` this command.

hi @iguoyr  - Thanks for your swift response. It shows as chaos-mesh:v2.0.7. So, I assume that we are trying to deploy 2.0.7 and not 2.1.3 however, even if we consider to deploy 2.0.7, why do you think we are getting the above error (mentioned in my previous notes)?  For now, let us consider that we would want to install 2.0.7 and let us know how do we get rid of the above issue. Thanks!

**Comment by iguoyr** [comment] 2022-03-21 08:34
@Prashanth-BP I think it is caused by the inconsistency between the helm chart version(v2.1.3) and the real component version(v2.0.7) of Chaos Mesh. The error log shows that the controller manager does not support leader election, because this feature only works in v2.1.x version.

If you want to install Chaos Mesh v2.0.7, you could refer to [this document](https://chaos-mesh.org/docs/2.0.7/production-installation-using-helm/). Or if you want to install Chaos Mesh v2.1.3, you could refer to [this document](https://chaos-mesh.org/docs/production-installation-using-helm/).

**Comment by Prashanth-BP** [comment] 2022-03-21 09:15
@iguoyr  - Thanks for your response. I have tried installing the 2.0.7 (on AWS EKS) after referring the documentation. Now, when I access the Dashboards, I get the attached errors. Unfortunately, I am unable to see any pods if I select any namespace within the Dashboard. Kindly help.
[ERRORS CHAOS MESH DASHBOARD.docx](https://github.com/chaos-mesh/chaos-mesh/files/8314218/ERRORS.CHAOS.MESH.DASHBOARD.docx)

**Comment by iguoyr** [comment] 2022-03-21 09:26
@Prashanth-BP It looks like the installation is failed, the crds(Custom Resource Definition) of Chaos Mesh are not installed on your Kubernetes cluster. What version of Kubernetes are you using? Do you have any logs when installing Chaos Mesh?

**Comment by Prashanth-BP** [comment] 2022-03-21 09:59
I do not have the logs however, the Kubernetes version is 

![image](https://user-images.githubusercontent.com/47818191/159239255-77b37c29-6de0-47ba-9b99-d7b16e497c4c.png)

**Comment by iguoyr** [comment] 2022-03-21 10:23
The version of Kubernetes looks good. How about installing crds manually, could try this command `curl -sSL https://mirrors.chaos-mesh.org/v2.0.7/crd.yaml | kubectl create --validate=false -f -`.

**Comment by Prashanth-BP** [comment] 2022-03-21 11:03
> The version of Kubernetes looks good. How about installing crds manually, could try this command `curl -sSL https://mirrors.chaos-mesh.org/v2.0.7/crd.yaml | kubectl create --validate=false -f -`.

hi @iguoyr - unfortunately, we are not authorized to curl and installing anything in our Environment. Let me try to uninstall and re-install. Meanwhile, is there any alternate fix available that we could apply before deploying (like on helm chart etc ?)

**Comment by iguoyr** [comment] 2022-03-21 11:19
@Prashanth-BP 

> is there any alternate fix available that we could apply before deploying (like on helm chart etc ?)

If installation is successful, the crds will be installed on your cluster, there is no need to install the crds manually. Actually the contents of crd are included in the helm chart templates.

> we are not authorized to curl and installing anything in our Environment.

BTW, is it possible that saving the content of the link as a file(this file is only 2.4M) and uploading it to your environment, and then applying it to Kubernetes?

**Comment by Prashanth-BP** [comment] 2022-03-23 07:50
@iguoyr  - We would like to install v2.1.3 however, the images are unavailable on Docker. Is there anyway you could upload the images for 2.1.3 on docker and let me know? I would ask our deployment team to pull the images from there. That would be a great help if you help us with this. Thanks!

**Comment by iguoyr** [comment] 2022-03-23 08:44
> @iguoyr - We would like to install v2.1.3 however, the images are unavailable on Docker. Is there anyway you could upload the images for 2.1.3 on docker and let me know? I would ask our deployment team to pull the images from there. That would be a great help if you help us with this. Thanks!

Sorry, we have no plan to push latest images to dockerhub. It's recommended that you pull the image from ghcr first, and push your own image to dockerhub, and you could set custom registry name when installing Chaos Mesh.

**Comment by Prashanth-BP** [comment] 2022-03-24 04:32
hi @iguoyr - Since there was no docker image available on the docker hub, we decided to install 2.0.7 and this is the error we see in Controller manager and Dashboard logs. Kindly help!

![controller-mananger-error](https://user-images.githubusercontent.com/47818191/159842697-1291dc4e-3ee0-40b9-bab0-00dcd4a2c4c3.jpg)

![dashboard-error](https://user-images.githubusercontent.com/47818191/159842719-029d0a3d-bd71-4710-b0ad-299081d1d0a3.jpg)

**Comment by iguoyr** [comment] 2022-03-24 05:27
> @iguoyr - Thanks for your response. I have tried installing the 2.0.7 (on AWS EKS, in a different AWS account) after referring the documentation. Now, when I access the Dashboards, I get the attached errors. Unfortunately, I am unable to see any pods if I select any namespace within the Dashboard. Kindly help.
> [ERRORS CHAOS MESH DASHBOARD.docx](https://github.com/chaos-mesh/chaos-mesh/files/8314218/ERRORS.CHAOS.MESH.DASHBOARD.docx)

It looks the same error as previous(the crds are not installed). Could you try `kubectl get crd | grep chaos-mesh` this command?

**Comment by Prashanth-BP** [comment] 2022-03-24 06:28
ok, here is the output. So, how do we troubleshoot this? Do we need to re-deploy the helm? In the previous communication, you have suggested to save the link as file and then uploading it to the environment and apply to the EKS. Where could we download this link as file? Could you please provide the URL (for v2.0.7)? If re-deploying is the quick solution the let me know.

![crds](https://user-images.githubusercontent.com/47818191/159855501-384a2697-bde2-4548-b42c-15fb360b20da.JPG)

**Comment by iguoyr** [comment] 2022-03-24 06:45
> ok, here is the output. So, how do we troubleshoot this? Do we need to re-deploy the helm? In the previous communication, you have suggested to save the link as file and then uploading it to the environment and apply to the EKS. Where could we download this link as file? Could you please provide the URL (for v2.0.7)? If re-deploying is the quick solution the let me know.
> 
> ![crds](https://user-images.githubusercontent.com/47818191/159855501-384a2697-bde2-4548-b42c-15fb360b20da.JPG)

Ohh, I see the crds are installed in `2021-06-xx`, the old version(v1.x.x) of crds are still existing on your Kubernetes cluster, which is not compatible with v2.x.x. 

Maybe you need to [uninstall the old version first](https://chaos-mesh.org/docs/next/uninstallation/), and then [re-install Chaos Mesh v2.0.7](https://chaos-mesh.org/docs/2.0.7/production-installation-using-helm/), it could solve this problem.

**Comment by Prashanth-BP** [comment] 2022-03-24 11:32
@iguoyr - I think we have finally managed to install 2.0.7 and things are looking good as of now. We could close both the incidents that I reported. I really appreciate your patience and help in this regard. Let me know if there is any forum I could give the feedback.. 👍 Thanks Again!

**Comment by iguoyr** [comment] 2022-03-25 04:51
> @iguoyr - I think we have finally managed to install 2.0.7 and things are looking good as of now. We could close both the incidents that I reported. I really appreciate your patience and help in this regard. Let me know if there is any forum I could give the feedback.. 👍 Thanks Again!

Glad to help. I'll close these two issues, feel free to re-open or create new issues if there is any problems.

**Closed by iguoyr** 2022-03-25 04:51 UTC
