### ISSUE TITLE
get error when use chaosd in dashbord

### ISSUE THREAD

**Issue by ycwdaaaa** [chaos-mesh/chaos-mesh#3095] opened 2022-04-01 10:19 UTC
Failed to apply chaos: : a secure url should begin with `https` rather than `http`, url: http://192.168.25.81:31767/api/attack/stress

**Comment by ycwdaaaa** [comment] 2022-04-01 12:47
I noticed I need to set she parameter when deploy chaos-mesh. But I got the new error:Failed to apply chaos: : Post "http://159.75.216.174:31767/api/attack/stress": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x06\x04\x00\x00\x00\x00\x00\x00\x05\x00\x00@\x00"

**Comment by iguoyr** [comment] 2022-04-01 12:58
@ycwdaaaa Hi, what version of chaosd and chaos-dashboard do you use? (Do you use the latest version? It seems this issue is related to the configuration of mTLS, which only should happened in the latest version.)

**Comment by iguoyr** [comment] 2022-04-01 13:23
> already got the root reason

As the problem is solved, I'll close this issue now :)

**Closed by iguoyr** 2022-04-01 13:23 UTC
Labels: type/bug

**Comment by ycwdaaaa** [comment] 2022-04-01 13:25
> @ycwdaaaa Actually it's a new feature in the latest version(on master branch), the mTLS can secure the connection between chaosd and chaos-controller-manager. And if you are interested in it, you could refer to [this document](https://chaos-mesh.org/docs/next/simulate-physical-machine-chaos/#deploy-chaosd-server) to config the chaosd.
> 
> This feature is not released, if you have any problems about it, feel free to open new issues :)

Thanks a lot， but now I got another problem.   chaosd throw the error:159.75.220.213 | DELETE   "/api/attack/215b6cc7-0e72-49d4-8cd4-592f60080583"
Error #01: error.api.internal_server_error: record not found

this happened when the chaos-mesh try to recover the experments.

**Comment by ycwdaaaa** [comment] 2022-04-01 13:26
it looks like the uuid is not correct?
