### ISSUE TITLE
Can't apply CRD Chaos-mesh 2.0.1 because of workflownodes

### ISSUE THREAD

**Issue by debek** [chaos-mesh/chaos-mesh#2281] opened 2021-09-06 11:55 UTC
## Bug Report
I can't APPLY CRD for chaos-mesh 2.0.1

**What version of Kubernetes are you using?**
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53437de67cac1e9fa54a3a09a28371d7", GitTreeState:"clean", BuildDate:"2021-10-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2592fa3a64c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-10-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1

```
**What version of Chaos Mesh are you using?**
2.0.1

**What did you do?**
kubectl apply -f crd.yaml   

**What did you expect to see?**
I want apply CRD

**What did you see instead?**
Error:
`The CustomResourceDefinition "workflownodes.chaos-mesh.org" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`

**Output of chaosctl**
```
customresourcedefinition.apiextensions.k8s.io/awschaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/dnschaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/gcpchaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/httpchaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/iochaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/jvmchaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/kernelchaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/networkchaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/podchaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/podhttpchaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/podiochaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/podnetworkchaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/schedules.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/stresschaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/timechaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/workflows.chaos-mesh.org created
The CustomResourceDefinition "workflownodes.chaos-mesh.org" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

**Comment by fewdan** [comment] 2021-09-07 03:29
@debek 
You can use "kubectl create -f" instead of "kubectl apply -f".

**Comment by debek** [comment] 2021-09-07 09:18
> @debek
> You can use "kubectl create -f" instead of "kubectl apply -f".

Why we have this issue? ArgoCD use "Apply" instead of "Create".
With manually "Create" it works.

**Comment by STRRL** [comment] 2021-09-07 10:40
Actually, it's the restriction of Kubernetes:

```
The CustomResourceDefinition "workflownodes.chaos-mesh.org" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

When you use `kubectl apply -f`, kubectl try to create the object with annotation `last-applied-configuration`, with the full content of the crd.

The root cause of this issue is the huge generated CRD file, including description and validation. And WOrkflowNode could embed an entire definition of `Container`, which makes the CRD larger.

I think the only way to resolve this issue without losing the schema/description of each resources is by using api-aggregation instead of CRD, but it needs a long way to go.

**Comment by STRRL** [comment] 2021-09-08 02:55
I am going to close this issue. Feel free to reopen it :smile_cat:

**Closed by STRRL** 2021-09-08 02:55 UTC

**Comment by YangKeao** [comment] 2021-09-08 05:58
Argo has an issue https://github.com/argoproj/argo-cd/issues/820 to track the problem. It seems to have been fixed by setting `"argocd.argoproj.io/sync-options": "Replace=true"`
